" 1. Install vim-plug
" curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
" 2. Install plugins
" :PlugInstall
if filereadable(expand('~/.vim/autoload/plug.vim'))
  call plug#begin()

  " Support for opening the files at specified:line
  Plug 'bogado/file-line'

  " Vertical alignment of text
  Plug 'godlygeek/tabular'

  " Git
  Plug 'tpope/vim-fugitive'
  map <silent> <leader>gb :Git blame<CR>
  map <silent> <leader>gd :Gvdiff HEAD<CR>

  " Files explorer
  Plug 'scrooloose/nerdtree'
  map <silent> <leader>t :NERDTreeFind<CR>
  let NERDTreeIgnore=['^target$[[dir]]']
  let g:NERDTreeQuitOnOpen = 1

  " Scala
  Plug 'derekwyatt/vim-scala'
  au BufRead,BufNewFile *.sbt set filetype=scala

  " Ident guides
  "Plug 'nathanaelkane/vim-indent-guides'
  "let g:indent_guides_enable_on_vim_startup = 1
  "let g:indent_guides_auto_colors = 0
  "let g:indent_guides_start_level = 2
  "let g:indent_guides_guide_size = 1
  "hi IndentGuidesOdd  ctermbg=234
  "hi IndentGuidesEven ctermbg=233

  call plug#end()
endif

if filereadable(expand("~/.vim/vimrc.local"))
  source(expand("~/.vim/vimrc.local"))
endif

set noet cc= fdm=indent
